### ISSUE TITLE
Throws error while using along with cloudflare adopter 

### ISSUE THREAD

**Issue by abdul-architect** [Playform/CompressAstro#251]
When using cloudflare adapter to deploy in pages. During built time I get an error with node:stream.

**Comment by NikolaRHristov** [comment]
Hi, can you paste your error log?

**Comment by wolf-yuan-6115** [comment]
Well, I managed to solve it by excluding some files:

Adding this to AstroCompress config fixed this issue for me:
```js
{
  Exclude: ["_routes.json", "_worker.mjs", "_noop-middleware.mjs", "renderers.mjs"]
}
```

![image](https://github.com/astro-community/AstroCompress/assets/58245644/f42f70ac-9f59-4b9e-99e0-7dbf9e7750c6)

**Comment by wolf-yuan-6115** [comment]
Well, I managed to solve it by excluding some files:

Adding this to AstroCompress config fixed this issue for me:
```js
{
  Exclude: ["_routes.json", "_worker.mjs", "_noop-middleware.mjs", "renderers.mjs"]
}
```

![image](https://github.com/astro-community/AstroCompress/assets/58245644/f42f70ac-9f59-4b9e-99e0-7dbf9e7750c6)
